### ISSUE TITLE
Tools added in last PR don't have multi-tool containers created

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/planemo-monitor#33]
Thanks for this very convenient setup!

I was checking, and the tools that I added in the last PR don't seem to have multi-tool containers created, for instance:

![image](https://user-images.githubusercontent.com/368478/104828004-a7c6ef00-585c-11eb-8c02-1cfe2114c996.png)

Is there a way I can help to make the CI create the PRs in the multi-tool container repo?

Thanks!

**Comment by bgruening** [comment]
@pcm32 see here: https://github.com/galaxyproject/planemo-monitor/pull/32

**Comment by pcm32** [comment]
Ok, I understand what happens now. The listing of tools is giving me all the installed versions of tools, however some of those versions are earlier than when I added the repo to planemo-monitor. As such, those earlier versions of the tools don't have containers. Do you think is relevant for completion that I try to add older tools to the multi-tool container setup? Given that this isn't really an issue of planemo-monitor, I'll close this.
